services:

  database:
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MARIADB_RANDOM_ROOT_PASSWORD: 1;
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - "./data/mariadb/data:/var/lib/mysql:Z"
    ports:
      - "8307:3306"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    hostname: mailpit
    restart: always
    ports:
      - "8025:8025" # WEB GUI
      - "1025:1025" # SMTP
    volumes:
      - "./data/mailpit-data:/data"  # Separate database
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_AUTH_ACCEPT_ANY: 1  # Disable authentication
      MP_DATABASE: /data
      MP_MAX_MESSAGES: 5000 # Maximum number of messages to store
      MP_VERBOSE: true # Enable debug logging
      MP_LOG_FILE: 
    healthcheck:
      test: ["CMD", "/mailpit", "readyz"]
      interval: 15s
      start_period: 10s
      timeout: 30s      # optional (default is 30s)
      retries: 3        # optional (default is 3)

  webapp:
    build:
      context: ./images/websrv-php
    container_name: ees_webapp
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      APACHE_DOCUMENT_ROOT: "/var/www/web/public"
      DB_HOST:
      DB_USER:
      DB_PASSWORD:
      DB_NAME:
    volumes:
      - "../src:/var/www:Z"
    ports:
      - "8082:80"
    depends_on:
      - database
      - mailpit

  structurizr:
    image: structurizr/lite
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - "../docs/structurizr:/usr/local/structurizr:Z"
    ports:
      - "8083:8080"
    profiles:
      - documentation
